language: node_js
cache: npm
node_js: 
  - 15

script:
  - npm run build
  - npm run test:coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: frontend